= Documentation Repository

This is the repository where the architecture documentation is collected and assets are generated.

== How Does It Work?

This repository has a GitHub Action workflow that reacts to any changes in the `.build` folder on the `master` branch.

The sources of all generated content are located under the `.build/src/**` folder:

* `.build/src/json/components` contains `.json` description files for all components of the documented system
* `.build/src/plantuml` contains hand-crafted diagrams

If any of the source input files or build script parts are changed, all images and documents are re-generated.
Any generated file that differs from its previous version is committed and pushed to the `master` branch.
This means documentation files are always up-to-date.

=== Automatic Updates

Automatically generating diagrams is nice and all, but the real interesting part is how the `.json` application descriptions are updated.

.Example: 'backend-service-1' is changed
[.text-center]
image:diagrams/extra/update-process.svg[]

Each application is responsible for generating and updating its own `.json` file.
Generally this is done by having the relevant information (e.g. dependents, dependencies, etc.) collected during the application's `master` build and generating the `.json` file.
If the overall application build (incl. tests) was successful, the `.json` file is automatically committed and pushed to this repository.

Since this commit will constitute a relevant change to the `.build` folder, the generation workflow will be executed, updating all affected images, documents, etc.

== Diagram Types

Currently, there are two types of diagrams with a few variations each.

=== "Application Context" Diagram

An "application context" diagram is focused on a specific application and shows that application's dependents and dependencies.
Dependents are other components of the overall system that are dependent on the focus application (e.g. using its API).
Dependencies are any components that are used by the focus application, like databases or other applications.

There are currently two variants of this type of diagram.

==== "Simple" Variants

The "simple" variant just renders all the components and their relationships.

.backend-service-1
[.text-center]
image:diagrams/components/simple_default/backend-service-1.svg[]

.backend-service-2
[.text-center]
image:diagrams/components/simple_default/backend-service-2.svg[]

==== "HTTP" Variants

The "http" variant renders all available data related to HTTP communication.
In this example, this includes the list of all HTTP endpoints used of a dependency.

.backend-service-1
[.text-center]
image:diagrams/components/http_poly/backend-service-1.svg[]

.backend-service-2
[.text-center]
image:diagrams/components/http_poly/backend-service-2.svg[]

==== "Full" Variants

The "full" variant renders all available data.
In this example, that will group all components by their `system` and `group` properties, as well as list the used HTTP endpoints of dependencies.

.backend-service-1
[.text-center]
image:diagrams/components/full_orthogonal/backend-service-1.svg[]

.backend-service-2
[.text-center]
image:diagrams/components/full_orthogonal/backend-service-2.svg[]

=== "Applications Overview" Diagram

An "applications overview" diagram combines the information of all applications into a single diagram.
This gives us an overview of our whole system with all communication paths / dependencies.

.top-to-bottom
[.text-center]
image:diagrams/overview/top-to-bottom_poly/overview.svg[]

.left-to-right
[.text-center]
image:diagrams/overview/left-to-right_poly/overview.svg[]
