@startuml

actor developer as dev
participant "'order-service'\nRepository" as sr
participant "'documentation'\nRepository" as dr

dev -> sr : push some change
activate sr
sr -> sr : build component
sr -> dr : checkout
activate dr
sr <--dr
deactivate dr
sr -> sr : combine component description parts
sr -> dr : commit & push updated 'order-service.json'
activate dr
deactivate sr
dr -> dr : generate diagrams, documents, etc.
dr -> dr : commit & push updated files

@enduml
