@startuml
'https://plantuml.com/deployment-diagram

folder "Platform" {
    frame "Application" {
        rectangle "Backend Service #1" as backendservice1 #lightgrey
        rectangle "Backend Service #2" as backendservice2 #skyblue;line.bold
    }
    rectangle "External Service #2" as externalservice2 #moccasin
}
folder "Other Project" {
    rectangle "External Service #3" as externalservice3 #lightcoral
}

backendservice1 -r-> backendservice2
backendservice2 -d-> externalservice2
backendservice2 -d-> externalservice3

@enduml
