@startuml
'https://plantuml.com/deployment-diagram

folder "Platform" {
    frame "Application" {
        rectangle "Frontend" as frontend #lightgrey
        rectangle "Backend Service #1" as backendservice1 #skyblue;line.bold
        rectangle "Backend Service #2" as backendservice2 #lightblue
        database "database" as backendservice1database
    }
    rectangle "External Service #1" as externalservice1 #moccasin
}

frontend -r-> backendservice1
backendservice1 -d-> backendservice1database
backendservice1 -r-> backendservice2
backendservice1 --> externalservice1

@enduml
